server:
  port: 8090

cluster:
  nacos:
    node1: 127.0.0.1:8848

spring:
  application:
    name: study-ribbon-server
  cloud:
    nacos:
      discovery:
        server-addr: ${cluster.nacos.node1}
        register-enabled: true
        group: study

